version: '3.4'
services:
  confluence:
    image: haxqer/confluence:9.2.0
    container_name: confluence-srv
    environment:
      - TZ=Asia/Bangkok
      - DB_HOST=172.20.1.10
      - DB_PORT=1521
      - DB_NAME=CONFLUENCE
      - DB_USER=confluence
      - DB_PASSWORD=admin123
      - DB_TYPE=oracle
    ports:
      - "8090:8090"
    volumes:
      - home_data:/var/confluence
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
