version: '3.4'
services:
  confluence:
    image: haxqer/confluence:9.2.0
    container_name: confluence
    environment:
      - TZ=Asia/Bangkok
      - DB_HOST=172.20.1.10
      - DB_PORT=1521
      - DB_NAME=CONFLUENCE
      - DB_USER=confluence
      - DB_PASSWORD=admin123
      - DB_TYPE=oracle
      - JVM_SUPPORT_RECOMMENDED_ARGS=-Dconfluence.word.import.maxsize=209715200
    ports:
      - "8090:8090"
    volumes:
      - /confluence/data:/var/confluence
      - /confluence/app:/opt/confluence
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
